---
title: "2.성별에 따른 월급 차이"
author: 하현주
date: July 30, 2020
output: github_document
---
```{r, include=F}
Sys.setenv("LANGUAGE"="EN")
library(foreign)             # SPSS 파일 로드
library(dplyr)               # 전처리
library(ggplot2)             # 시각화
library(readxl)              # 엑셀 파일 불러오기

#데이터 불러오기
raw_welfare <-read.spss(file="Koweps_hpc10_2015_beta1.sav",
                        to.data.frame=T)

#복사본 만들기
welfare<- raw_welfare

welfare <- rename(welfare, 
                  sex =h10_g3,
                  birth =h10_g4,
                  marriage =h10_g10,
                  religion=h10_g11,
                  income=p1002_8aq1,
                  code_jib=h10_eco9,
                  code_region=h10_reg7)

```


## 2. 성별에 따른 월급 차이 
 데이터 분석을 통해 성별에 따라 월급차이를 파악하고자 함. 
 성별과 월급 두 변수를 검토하고 전처리한 후 변수 간의 관계를 분석. 

### 분석 절차
 1. 변수 검토 및 전처리
 성별 -> 월급
 
 2.변수 간 관계 분석
 성별 월급 평균표 만들기 -> 그래프 만들기 
 
### 성별 변수 검토 및 전처리 

#### 1. 변수 검토하기
```{r, eval=F}
class(welfare$sex)
table(welfare$sex)
```
#### 2. 전처리
테이블 이상치 확인하여 이상치에 NA부여하여 결측처리함. 

```{r, eval=F}
#이상치 확인
table(welfare$sex)
```
이상치 결측처리
```{r, eval=T}
#이상치 결측 처리
welfare$sex <- ifelse(welfare$sex == 9, NA, welfare$sex)
#결측치 확인
table(is.na(welfare$sex))
#성별 항목 이름 부여
welfare$sex <- ifelse(welfare$sex==1, "male", "female")
table(welfare$sex)
qplot(welfare$sex)
```

### 월급 변수 검토 및 전처리

#### 1. 변수 검토하기

```{r,eval=T, warning=F, message=F}
class(welfare$income)
summary(welfare$income)
qplot(welfare$income)
qplot(welfare$income)+xlim(0,1000)
```

#### 2. 전처리

```{r,eval=T}
#이상치 확인
summary(welfare$income)
#이상치 결측 처리
welfare$income<-ifelse(welfare$income %in% c(0,9999), NA, welfare$income)
#결측치 확인
table(is.na(welfare$income))
```
### 성별에 따른 월급 차이 분석하기

#### 1. 성별 월급 평균표 만들기
변수 간 관계 분석
```{r,eval=T}
sex_income <-welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(sex) %>% 
  summarise(mean_income = mean(income))

sex_income
```
#### 2. 그래프 만들기
분석결과 막대그래프로 표현
```{r,eval=T}
ggplot(data=sex_income, aes(x=sex, y=mean_income)) + geom_col()
```