---
title: "연령대에 따른 월급 차이"
author: 하현주
date: July 31, 2020
output: github_document
---

```{r, include=F}
library(foreign)             # SPSS 파일 로드
library(dplyr)               # 전처리
library(ggplot2)             # 시각화
library(readxl)              # 엑셀 파일 불러오기

# 데이터 불러오기
raw_welfare <- read.spss(file = "Koweps_hpc10_2015_beta1.sav",
                         to.data.frame = T)

# 복사본 만들기
welfare <- raw_welfare

# 변수 이름 변경하기기
welfare <- rename(welfare,
                  sex = h10_g3,            # 성별
                  birth = h10_g4,          # 태어난 연도
                  marriage = h10_g10,      # 혼인 상태
                  religion = h10_g11,      # 종교
                  income = p1002_8aq1,     # 월급
                  code_job = h10_eco9,     # 직종 코드
                  code_region = h10_reg7)  # 지역 코드

#birth 이상치 결측 처리
welfare$birth <- ifelse(welfare$birth ==9999,NA,welfare$birth)

#나이 파생변수 만들기
welfare$age<-2015-welfare$birth+1

```

## 4. 연령대에 따른 월급 차이

### 분석 절차
변수 검토 및 전처리
 -연령대
 -월급
 
변수 간 관계 분석
 -연령대별 월급 평균표 만들기
 -그래프 만들기
 
```{r, results="hide"}
welfare$age <-2015 - welfare$birth +1
```

### 연령대 변수 검토 및 전처리하기

```{r, results="hide"}

```

#### 1. 파생변수 만들기 - 연령대

 나이 변수를 이용해 연령대 변수 만들기
 초년(30세 미만), 중년(30~59세), 노년(60세 이상)
```{r, results="hide"}
welfare<-welfare %>% 
  mutate(ageg=ifelse(age < 30, "young", ifelse(age <= 59, "middle", "old")))

table(welfare$ageg)

qplot(welfare$ageg)
```

### 연령대에 따른 월급 차이 분석하기

#### 1. 연령대별 월급 평균표 만들기

```{r, results="hide"}
ageg_income <- welfare %>%
 filter(!is.na(income)) %>%
 group_by(ageg) %>%
 summarise(mean_income = mean(income))

ageg_income  
```
#### 2. 그래프 만들기

```{r, results="hide"}
ggplot(data=ageg_income, aes(x=ageg, y=mean_income))+geom_col()
```

#### 막대 정렬 : 초년, 중년, 노년 나이 순
초년, 중년, 노년 나이 순으로 정렬되도록
scale_x_discrete(limit=c())에 범주 순서를 지정함. 
```{r, results="hide"}
ggplot(data=ageg_income, aes(x=ageg, y=mean_income))+
  geom_col()+
  scale_x_discrete(limits=c("young", "middle", "old"))
```

표와 그래프를 보면 중년이 280만원 정도로 가장 많은 월급을 받고, 그 다음은 초년이 163만원, 노년이 125만원으로 가장 낮은 월급을 받는다. 